[package]
name = "mdoc"
version = "0.1.1"
authors = ["Knut Magnus Aasrud <km@aasrud.com>"]
description = "Modern PDF creation through Markdown and LaTeX"
edition = "2021"
license-file = "LICENSE"
homepage = "https://github.com/kmaasrud/mdoc"
repository = "https://github.com/kmaasrud/mdoc"
include = [
    "**/*.rs",
    "**/*.tex",
    "**/*.lua",  
]


[dependencies]
dirs = "4.0"
chrono = "0.4"
ignore = "0.4"
ureq = "2.3"
serde = { version = "1.0", features = ["derive"] }
toml = "0.5"
url = "2.2"

# Error handling
anyhow = "1.0"
thiserror = "1.0"

# CLI
structopt = "0.3"

# LaTeX
tectonic = { version = "0.8", default-features = false, features = ["geturl-reqwest", "native-tls-vendored"] }


# VCPKG
[package.metadata.vcpkg]
git = "https://github.com/microsoft/vcpkg"
rev = "master"
[package.metadata.vcpkg.target]
x86_64-apple-darwin = { install = ["freetype","harfbuzz[icu,graphite2]"] }
aarch64-apple-darwin = { triplet = "arm64-osx", install = ["freetype","harfbuzz[icu,graphite2]"] }
x86_64-unknown-linux-gnu = { install = ["fontconfig","freetype","harfbuzz[icu,graphite2]"] }
x86_64-pc-windows-msvc = { triplet = "x64-windows-static", install = ["fontconfig","freetype","harfbuzz[icu,graphite2]"] }
