[package]
name = "djoc"
version = "0.1.0"
authors = ["Knut Magnus Aasrud <km@aasrud.com>"]
description = "Modern document writing with Djot"
edition = "2021"
license-file = "LICENSE"
homepage = "https://git.sr.ht/~kmaasrud/djoc"
repository = "https://git.sr.ht/~kmaasrud/djoc"
include = ["src/**/*.html", "src/**/*.lua", "src/**/*.rs", "src/**/*.tex"]


[dependencies]
anyhow = "1.0.69"
clap = { version = "4.1.4", default-features = false, features = [
    "cargo",
    "derive",
    "error-context",
    "help",
    "usage",
    "std",
] }
dirs = "4.0.0"
jotdown = "0.1.0"
log = "0.4.17"
rayon = "1.6.1"
serde = { version = "1.0.152", features = ["derive"] }
stderrlog = "0.5.4"
tectonic = { version = "0.12.0", default-features = false, features = [
    "geturl-reqwest",
    "native-tls-vendored",
] }
thiserror = "1.0.38"
time = { version = "0.3.17", default-features = false, features = [
    "formatting",
    "local-offset",
    "macros",
    "parsing",
] }
toml = "0.7.2"
ureq = "2.6.2"
url = "2.3.1"

[profile.release]
codegen-units = 1
lto = true
strip = true


# VCPKG
[package.metadata.vcpkg]
git = "https://github.com/microsoft/vcpkg"
rev = "master"
[package.metadata.vcpkg.target]
x86_64-apple-darwin = { install = ["freetype", "harfbuzz[icu,graphite2]"] }
aarch64-apple-darwin = { triplet = "arm64-osx", install = [
    "freetype",
    "harfbuzz[icu,graphite2]",
] }
x86_64-unknown-linux-gnu = { install = [
    "fontconfig",
    "freetype",
    "harfbuzz[icu,graphite2]",
] }
x86_64-pc-windows-msvc = { triplet = "x64-windows-static", install = [
    "fontconfig",
    "freetype",
    "harfbuzz[icu,graphite2]",
] }
