title = "MDoc"
baseURL = "https://kmaasrud.com/mdoc"
languageCode = "en"
disableKinds = ["taxonomy", "term"]

[author]
name = "Knut Magnus Aasrud"

[markup.goldmark.parser.attribute]
block = true

[markup.highlight]
guessSyntax = false
style = "github"

[[menu.main]]
identifier = "usage"
name = "Usage"
weight = 10

[[menu.main]]
identifier = "markdown"
name = "Markup"
weight = 20
