output_format = "html"

[[document]]
title = "Djoc documentation"
author = [{name = "Knut Magnus Aasrud", email = "km@aasrud.com"}]
chapters = [
    { path = "src/introduction.dj" },
    "src/getting-started.dj",
]
