pandoc:
	pandoc docs.md -s -o out/index.html --template=template.html --katex --toc --toc-depth=2
	pandoc docs.md -s -o out/docs.html --template=template.html --katex --toc --toc-depth=2
	pandoc install.md -s -o out/install.html --template=template.html --katex
